"""Recover XIntMath.sqrtTable from the canonical metadata field initializer.

Metadata layout reference: Il2CppDumper v6.7.46 MetadataClass.cs.
The cctor loads the field via GOT 0x405B548 before InitializeArray and stores
its 256-element result at static +0x18. Field-name SHA-1 verifies the payload.
"""
import hashlib
import json
import struct
from pathlib import Path
from disassemble_spmove_runtime import file_offset

ROOT = Path(__file__).resolve().parents[1]
FIELD_NAME = '5F4A8854DFF73E49FE6168022DA8913860542337'
METADATA_SHA = '92fae52ec4dc570929eb7b99d2083fd6ab6016cbbaa30f87e87ac6732bb1e42e'
BINARY_SHA = '2a3ffe74b6c2d195b54db5b1c2616d289ab19d27426a4c4de041a916c214d496'


def recover():
    metadata = (ROOT/'.local/il2cpp/global-metadata.dat').read_bytes()
    binary = (ROOT/'.local/il2cpp/libil2cpp.so').read_bytes()
    if hashlib.sha256(metadata).hexdigest() != METADATA_SHA or hashlib.sha256(binary).hexdigest() != BINARY_SHA:
        raise ValueError('canonical source hash mismatch')
    if struct.unpack_from('<II', metadata) != (0xFAB11BAF, 24):
        raise ValueError('unsupported metadata format')
    string_offset, string_size = struct.unpack_from('<II', metadata, 24)
    fields_offset, fields_size = struct.unpack_from('<II', metadata, 96)
    default_offset, default_size = struct.unpack_from('<II', metadata, 64)
    data_offset, data_size = struct.unpack_from('<II', metadata, 72)
    name_index = metadata.find(FIELD_NAME.encode()+b'\0', string_offset, string_offset+string_size) - string_offset
    if name_index < 0:
        raise ValueError('sqrt field absent')
    fields = [i for i in range(fields_size//12)
              if struct.unpack_from('<I', metadata, fields_offset+i*12)[0] == name_index]
    if len(fields) != 1:
        raise ValueError('ambiguous field')
    defaults = [struct.unpack_from('<iii', metadata, default_offset+i*12)
                for i in range(default_size//12)]
    matches = [row for row in defaults if row[0] == fields[0]]
    if len(matches) != 1:
        raise ValueError('ambiguous initializer')
    index = matches[0][2]
    if not 0 <= index <= data_size-1024:
        raise ValueError('initializer out of bounds')
    payload = metadata[data_offset+index:data_offset+index+1024]
    if hashlib.sha1(payload).hexdigest().upper() != FIELD_NAME:
        raise ValueError('initializer field digest mismatch')
    slot = struct.unpack_from('<Q', binary, file_offset(binary, 0x405B548))[0]
    script = json.loads((ROOT/'.local/tools/Il2CppDumper/script.json').read_text())
    entries = [r for r in script['ScriptMetadata'] if r['Address'] == slot]
    if len(entries) != 1 or entries[0]['Name'] != 'Field$<PrivateImplementationDetails>.'+FIELD_NAME:
        raise ValueError('cctor field pointer mapping mismatch')
    return {
        'schema_version': 'football.recovery.native_sqrt_table.v1',
        'binary_sha256': BINARY_SHA, 'metadata_sha256': METADATA_SHA,
        'initializer_field': FIELD_NAME, 'field_index': fields[0],
        'metadata_payload_offset': hex(data_offset+index),
        'payload_sha256': hashlib.sha256(payload).hexdigest(),
        'cctor': '0x1B653C8', 'cctor_field_got': '0x405B548',
        'field_metadata_slot': hex(slot), 'values': list(struct.unpack('<256i', payload)),
    }


if __name__ == '__main__':
    report = recover()
    (ROOT/'Recovery/Normalized/native_sqrt_table.json').write_text(json.dumps(report, indent=2)+'\n')
    rows = [', '.join(map(str, report['values'][i:i+16])) for i in range(0,256,16)]
    header = ('#pragma once\n#include <array>\n#include <cstdint>\n'
              'namespace football::physics::recovered {\n'
              '// Generated by Tools/recover_native_sqrt_table.py from canonical metadata.\n'
              'inline constexpr std::array<std::int32_t, 256> kNativeSqrtTable{{\n    '
              + ',\n    '.join(rows) + '\n}};\n}\n')
    (ROOT/'Reference/FootballPhysics/NativeSqrtTable.h').write_text(header)
    print('NATIVE_SQRT_TABLE: recovered 256 integers; metadata SHA-1/256 verified')
